# Create toy population dataset

In [1]:
import numpy as np

In [2]:
pop_size = 12
str_len = 10
half_len = str_len//2

In [3]:
pop = np.array([np.random.permutation(np.arange(0, str_len)) for n in np.arange(pop_size)])
pop

array([[0, 3, 1, 4, 5, 9, 7, 2, 8, 6],
       [9, 5, 1, 8, 2, 0, 7, 3, 6, 4],
       [3, 9, 0, 1, 7, 2, 6, 5, 8, 4],
       [6, 7, 4, 5, 8, 3, 2, 1, 9, 0],
       [9, 1, 3, 2, 8, 6, 7, 0, 4, 5],
       [4, 0, 2, 3, 6, 7, 1, 8, 9, 5],
       [2, 8, 1, 4, 5, 9, 0, 6, 3, 7],
       [3, 0, 6, 9, 1, 4, 7, 5, 2, 8],
       [4, 6, 1, 8, 2, 3, 5, 7, 0, 9],
       [3, 9, 8, 1, 5, 7, 2, 0, 6, 4],
       [2, 6, 1, 3, 7, 4, 8, 5, 9, 0],
       [0, 2, 4, 8, 9, 7, 5, 1, 3, 6]])

# Sequence Selection on a single parent array

In [4]:
def vecArange(starts, delta):
    return np.repeat(np.expand_dims(starts, 1), delta, axis=1)+np.arange(0, delta)

In [5]:
seq_start = np.random.randint(0,half_len,pop_size)
seq_start

array([1, 3, 0, 1, 4, 4, 3, 0, 0, 3, 3, 3])

In [6]:
pop

array([[0, 3, 1, 4, 5, 9, 7, 2, 8, 6],
       [9, 5, 1, 8, 2, 0, 7, 3, 6, 4],
       [3, 9, 0, 1, 7, 2, 6, 5, 8, 4],
       [6, 7, 4, 5, 8, 3, 2, 1, 9, 0],
       [9, 1, 3, 2, 8, 6, 7, 0, 4, 5],
       [4, 0, 2, 3, 6, 7, 1, 8, 9, 5],
       [2, 8, 1, 4, 5, 9, 0, 6, 3, 7],
       [3, 0, 6, 9, 1, 4, 7, 5, 2, 8],
       [4, 6, 1, 8, 2, 3, 5, 7, 0, 9],
       [3, 9, 8, 1, 5, 7, 2, 0, 6, 4],
       [2, 6, 1, 3, 7, 4, 8, 5, 9, 0],
       [0, 2, 4, 8, 9, 7, 5, 1, 3, 6]])

In [7]:
seq = vecArange(seq_start,half_len)
seq

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8],
       [3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7]])

In [8]:
subseq = pop[np.arange(pop.shape[0])[:, None], seq]
subseq

array([[3, 1, 4, 5, 9],
       [8, 2, 0, 7, 3],
       [3, 9, 0, 1, 7],
       [7, 4, 5, 8, 3],
       [8, 6, 7, 0, 4],
       [6, 7, 1, 8, 9],
       [4, 5, 9, 0, 6],
       [3, 0, 6, 9, 1],
       [4, 6, 1, 8, 2],
       [1, 5, 7, 2, 0],
       [3, 7, 4, 8, 5],
       [8, 9, 7, 5, 1]])

## Remove subsequences from other parents

In [9]:
pop_roll = np.roll(pop,1,axis=0)
pop_roll

array([[0, 2, 4, 8, 9, 7, 5, 1, 3, 6],
       [0, 3, 1, 4, 5, 9, 7, 2, 8, 6],
       [9, 5, 1, 8, 2, 0, 7, 3, 6, 4],
       [3, 9, 0, 1, 7, 2, 6, 5, 8, 4],
       [6, 7, 4, 5, 8, 3, 2, 1, 9, 0],
       [9, 1, 3, 2, 8, 6, 7, 0, 4, 5],
       [4, 0, 2, 3, 6, 7, 1, 8, 9, 5],
       [2, 8, 1, 4, 5, 9, 0, 6, 3, 7],
       [3, 0, 6, 9, 1, 4, 7, 5, 2, 8],
       [4, 6, 1, 8, 2, 3, 5, 7, 0, 9],
       [3, 9, 8, 1, 5, 7, 2, 0, 6, 4],
       [2, 6, 1, 3, 7, 4, 8, 5, 9, 0]])

In [31]:
children = np.empty((pop.shape[0],str_len),int)
for n, seq in enumerate(subseq):
    child = pop_roll[n][np.isin(pop_roll[n],seq,invert=True)]
    child = np.insert(seq,seq_start[n],child)
    children[n] = child
print(pop[1])
# print(pop_roll[1])
print(children[1])

[9 5 1 8 2 0 7 3 6 4]
[8 2 0 1 4 5 9 6 7 3]


# Sequence Selection with combined parent arrays

In [111]:
parents = np.concatenate((pop,pop_roll),axis=1).reshape(-1,2,str_len)
parents

array([[[0, 4, 2, 1, 6, 7, 8, 3, 5, 9],
        [6, 3, 0, 9, 5, 8, 1, 2, 4, 7]],

       [[9, 0, 1, 8, 4, 6, 7, 2, 5, 3],
        [0, 4, 2, 1, 6, 7, 8, 3, 5, 9]],

       [[6, 3, 1, 5, 8, 7, 4, 9, 2, 0],
        [9, 0, 1, 8, 4, 6, 7, 2, 5, 3]],

       [[8, 9, 4, 5, 3, 0, 7, 2, 6, 1],
        [6, 3, 1, 5, 8, 7, 4, 9, 2, 0]],

       [[8, 3, 7, 0, 1, 9, 6, 4, 2, 5],
        [8, 9, 4, 5, 3, 0, 7, 2, 6, 1]],

       [[6, 1, 3, 2, 5, 7, 8, 9, 4, 0],
        [8, 3, 7, 0, 1, 9, 6, 4, 2, 5]],

       [[6, 4, 8, 7, 2, 5, 0, 9, 1, 3],
        [6, 1, 3, 2, 5, 7, 8, 9, 4, 0]],

       [[4, 2, 1, 6, 7, 8, 5, 3, 9, 0],
        [6, 4, 8, 7, 2, 5, 0, 9, 1, 3]],

       [[9, 1, 7, 0, 4, 2, 3, 5, 8, 6],
        [4, 2, 1, 6, 7, 8, 5, 3, 9, 0]],

       [[3, 8, 5, 0, 7, 2, 9, 6, 1, 4],
        [9, 1, 7, 0, 4, 2, 3, 5, 8, 6]],

       [[1, 7, 4, 5, 6, 0, 9, 3, 8, 2],
        [3, 8, 5, 0, 7, 2, 9, 6, 1, 4]],

       [[6, 3, 0, 9, 5, 8, 1, 2, 4, 7],
        [1, 7, 4, 5, 6, 0, 9, 3, 8, 2]]])

In [153]:
parents

array([[[0, 4, 2, 1, 6, 7, 8, 3, 5, 9],
        [6, 3, 0, 9, 5, 8, 1, 2, 4, 7]],

       [[9, 0, 1, 8, 4, 6, 7, 2, 5, 3],
        [0, 4, 2, 1, 6, 7, 8, 3, 5, 9]],

       [[6, 3, 1, 5, 8, 7, 4, 9, 2, 0],
        [9, 0, 1, 8, 4, 6, 7, 2, 5, 3]],

       [[8, 9, 4, 5, 3, 0, 7, 2, 6, 1],
        [6, 3, 1, 5, 8, 7, 4, 9, 2, 0]],

       [[8, 3, 7, 0, 1, 9, 6, 4, 2, 5],
        [8, 9, 4, 5, 3, 0, 7, 2, 6, 1]],

       [[6, 1, 3, 2, 5, 7, 8, 9, 4, 0],
        [8, 3, 7, 0, 1, 9, 6, 4, 2, 5]],

       [[6, 4, 8, 7, 2, 5, 0, 9, 1, 3],
        [6, 1, 3, 2, 5, 7, 8, 9, 4, 0]],

       [[4, 2, 1, 6, 7, 8, 5, 3, 9, 0],
        [6, 4, 8, 7, 2, 5, 0, 9, 1, 3]],

       [[9, 1, 7, 0, 4, 2, 3, 5, 8, 6],
        [4, 2, 1, 6, 7, 8, 5, 3, 9, 0]],

       [[3, 8, 5, 0, 7, 2, 9, 6, 1, 4],
        [9, 1, 7, 0, 4, 2, 3, 5, 8, 6]],

       [[1, 7, 4, 5, 6, 0, 9, 3, 8, 2],
        [3, 8, 5, 0, 7, 2, 9, 6, 1, 4]],

       [[6, 3, 0, 9, 5, 8, 1, 2, 4, 7],
        [1, 7, 4, 5, 6, 0, 9, 3, 8, 2]]])

In [154]:
seq_start = np.random.randint(0,half_len,pop_size).repeat(2) #repeat is so pairs of parents have same subseq
seq_start

array([3, 3, 4, 4, 2, 2, 3, 3, 4, 4, 3, 3, 3, 3, 0, 0, 2, 2, 4, 4, 2, 2,
       0, 0])

In [172]:
parent_seq = vecArange(seq_start,half_len).reshape(-1,2,half_len)
parent_seq

array([[[3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7]],

       [[4, 5, 6, 7, 8],
        [4, 5, 6, 7, 8]],

       [[2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6]],

       [[3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7]],

       [[4, 5, 6, 7, 8],
        [4, 5, 6, 7, 8]],

       [[3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7]],

       [[3, 4, 5, 6, 7],
        [3, 4, 5, 6, 7]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6]],

       [[4, 5, 6, 7, 8],
        [4, 5, 6, 7, 8]],

       [[2, 3, 4, 5, 6],
        [2, 3, 4, 5, 6]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [196]:
parents[np.arange(parents.shape[0])[:, None], parent_seq]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (12,1) (12,2,5) 